config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  resources :stories do
    get 'map'
    resources :placemarks do
    end
  end
	get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}
end

app/models/placemark.rb
class Placemark < ActiveRecord::Base
  belongs_to :story
  validates_presence_of :name, :message => "You must enter a name for this placemark" 
  validates_presence_of :lat, :message => "Use the interactive location selector to set latitude" 
  validates_presence_of :lng, :message => "Use the interactive location selector to set longitude" 
  default_scope {order('story_order ASC')}

  def index
    story.placemarks.order('id ASC').index(self) + 1
  end

  def all_next
    # should this be filtering on story_order instead of ID?
    story.placemarks.where('id > ?', id)
  end

  def all_prev
    # same as all_next re: story_order
    story.placemarks.where('id < ?', id)
  end

  def next
    all_next.first
  end

  def prev
    all_prev.last
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  has_many :placemarks, :dependent => :destroy
  validates_presence_of :name, :message => "You must enter a name for this story"

  def generate_GeoJSON
    @geojson = Array.new
    placemarks.all.each do |placemark|
      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [placemark.lng, placemark.lat]
        },
        properties: {
          name: placemark.name,
          description: placemark.description,
          image: placemark.image_data,
          image_alt: placemark.image_alt,
          link: placemark.link,
          :'marker-color' => '#f00'
        }
      }
    end
    return @geojson
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :stories, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # if user is logged in, return current_user, else return guest_user.
  def current_or_guest_user
    if current_user
      if session[:guest_user_id] && session[:guest_user_id] != current_user.id
        logging_in
        guest_user(with_retry = false).try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with current session,
  # creating one as needed.
  def guest_user(with_retry = true)
    # Cache the value the first time it's received.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user if with_retry
  end

  private

  # called when the user logs in, 
  # transfers record ownership from guest to new user.
  def logging_in
    guest_stories = guest_user.stories.all
    guest_stories.each { |story| story.update(user_id: current_user.id) }
  end

  def create_guest_user
    u = User.create(:email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end

end

app/controllers/placemarks_controller.rb
class PlacemarksController < ApplicationController
helper_method :current_or_guest_user

  def new
    @story = current_or_guest_user.stories.find(params[:story_id])
    @placemark = Placemark.new()
  end

  def create
    @story = current_or_guest_user.stories.find(params[:story_id])
    @placemark = @story.placemarks.new(placemark_params)
    if @placemark.save
      if params[:commit] === "Save Placemark"
        redirect_to new_story_placemark_path(@story)
      else
        redirect_to @story
      end
    else
      render :new
    end
  end

  def edit
    @story = current_or_guest_user.stories.find(params[:story_id])
    @placemark = @story.placemarks.find(params[:id])
  end

  def update
    @story = current_or_guest_user.stories.find(params[:story_id])
    @placemark = @story.placemarks.find(params[:id])
    if @placemark.update(placemark_params)
      if params[:commit] === "Save Placemark"
        if @placemark.next
          redirect_to edit_story_placemark_path(@story, @placemark.next)
        else
          redirect_to new_story_placemark_path(@story)
        end
      else
        redirect_to @story
      end
    else
      render :edit
    end
  end

  def destroy
    @story = current_or_guest_user.stories.find(params[:story_id])
    @placemark = @story.placemarks.find(params[:id])
    @placemark.destroy
    redirect_to @story
  end

  private
  def placemark_params
    params.require(:placemark).permit(:name, :description, :lat, :lng, :image_data, :image_alt, :link, :story_order)
  end

end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  layout nil
 
  def index
    headers['Content-Type'] = 'application/xml'
    respond_to do |format|
      format.xml {}
    end
  end
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
helper_method :current_or_guest_user

  def index
    @stories = current_or_guest_user.stories.all
  end

  def show
    @story = Story.find(params[:id])
    @placemarks = @story.placemarks.all
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @story.generate_GeoJSON}
    end
  end

  def new
    @story = current_or_guest_user.stories.new
  end

  def create
    @story = current_or_guest_user.stories.new(story_params)
      if @story.save
        @placemark = @story.placemarks.new
        redirect_to new_story_placemark_path(@story)
      else
        render :new
      end
  end

  def edit
    @story = current_or_guest_user.stories.find(params[:id])
  end

  def update
    @story = current_or_guest_user.stories.find(params[:id])
    if @story.update(story_params)
      redirect_to @story
    else
      render :edit
    end
  end

  def destroy
    @story = current_or_guest_user.stories.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  def map
    @story = Story.find(params[:story_id])
    render :layout => false
  end

  private
  def story_params
    params.require(:story).permit(:name, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
helper_method :current_or_guest_user

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def setPlacemarkViewStatus
    if @story.user_id != current_or_guest_user.id
      @placemarks_owner_class = 'not-owner'
    end
    if @placemarks.none?
    	@no_placemarks = true
    	@placemarks_link_class = 'disabled'
    end
  end

end

app/views/layouts/_favicon.html.erb
<% %w(16 32 96 192 194).each do |size| %>
  <%= favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>
<% %w(57 60 72 76 114 120 144 152 180 192).each do |size| %>
  <%= favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>
  <link rel='manifest' href='/manifest.json'>
  <meta name='apple-mobile-web-app-title' content='Placemark Story'>
  <meta name='application-name' content='Placemark Story'>
  <meta name='msapplication-TileColor' content='#00aba9'>
  <meta name='msapplication-TileImage' content='/mstile-144x144.png'>
  <meta name='theme-color' content='#ffffff'>

app/views/layouts/application.html.erb
<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <title>Placemark Story</title>
  <meta name='description' content='Placemark Story: the easiest way to create and share interactive map stories'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
<%= render 'layouts/favicon' %>
  <!--[if lt IE 9]]>
    <%= javascript_include_tag 'html5shiv', 'data-turbolinks-track'=> true %>
    <%= stylesheet_link_tag 'L.Control.Locate.ie', 'data-turbolinks-track'=> true %>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  <div class='login-input'>
    <% if user_signed_in? %>
      <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path %> |
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
    </div>
    <h1>
      <span class='title-word1'>Placemark</span><span class='title-word2'>Story</span>
    </h1>
    <nav>
      <ul>
        <li><%= link_to 'About', root_path %></li>
        <li><%= link_to 'New Map Story', new_story_path %></li>
        <li><%= link_to 'Your Map Stories', stories_path %></li>
      </ul>
    </nav>
    <div id='logo'></div>
  </header>
  <section>
  <%= yield %>
  <% if notice %>
    <div class='alert green-alert login-alert'>
      <p>
        <%= notice %>
      </p>
    </div>
  <% end %>
  <% if alert %>
    <div class='alert red-alert login-alert'>
      <p>
        <%= alert %>
      </p>
    </div>
  <% end %>
  </section>
  <footer>
    <span class='contribue'>
      Powered by <%= link_to 'Mapbox', 'https://www.mapbox.com/', class: 'mapbox-logo' %>. <%= link_to '<i class="fa icon-github"></i> Read more and contribute'.html_safe, 'https://github.com/nbumbarger/placemark_story' %>
    </span>
    <span class='credits'>
      Made with <i class='fa icon-heart'></i> by <%= link_to 'Nick Bumbarger', 'http://www.nickbumbarger.com' %>
    </span>
  </footer>
</body>
</html>

app/views/placemark/new.html.erb
<% if @placemark.errors.any? %>
<ul>
  <% placemark.errors.full_messages.each do |err| %>
  <li><%= err %></li>
  <% end %>
</ul>
<% end %>

<%= form_for [@story, @placemark] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :synopsis %>
  <%= f.text_field :synopsis %>
  <%= f.label :full_text %>
  <%= f.text_field :full_text %>
  <%= f.label :lat %>
  <%= f.text_field :lat %>
  <%= f.label :lon %>
  <%= f.text_field :lon %>
  <%= f.submit %>
<% end %>d

app/views/placemarks/edit.html.erb
<h2>Edit Map Story: <%= @story.name %>/<%= @placemark.name %></h2>
<% if @placemark.errors.any? %>
  <div class='alert red-alert'>
    <h3><%= pluralize(@placemark.errors.count, 'error') %> prevented this placemark from being saved:</h3>
    <ul>
    <% @placemark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% if @placemark.errors[:lat].any? || @placemark.errors[:lng].any? %>
    <% @location_selector_status = 'field_with_errors' %>
  <% end %>
<% end %>
<div class='widget placemark-entry'>
<%= form_for [@story, @placemark] do |f| %>
  <h3>Enter story fragment text</h3>
    <%= f.text_field :name,
                     placeholder: 'Required: Enter a title for this story fragment',
                     autofocus: true,
                     autocomplete: :off %>
    <%= f.text_area  :description,
                     placeholder: 'Optional: Enter a description for this story fragment',
                     autocomplete: :off %>
    <%= f.text_field :link,
                     placeholder: 'Optional: Add a hyperlink to include with this placemark',
                     autocomplete: :off %>                   
  </div>
  <div class='location-selector <%= @location_selector_status %>'>
    <div id='map'>
      <pre id='coordinates' class='ui-coordinates'></pre>
    </div>
    <div class='caption'>
      Drag <i class='fa icon-map-marker-reticule'></i> to set location. Use <i class='fa icon-search fa-fw'></i> to find address or <i class='fa icon-map-marker-current fa-fw'></i> to use current.
    </div>
  </div>
  <div class='widget image-editor'>
    <h3>Optional: Upload and crop image</h3>
      <div class="image-widget-container">
      <div class='cropit-image-preview'></div>
      <div class='image-controls'>
       <button class='select-image-button' type='button'>Select Image</button>
       <input type='range' class='cropit-image-zoom-input'>
       <div class='image-size-label'>Zoom</div>
        <textarea class='image-alt' placeholder='Enter image alt text' autocomplete='off' type='text' name='alt_text' id='alt_text'></textarea>
      </div>
      <input type='file' class='cropit-image-input'>
    </div>
  </div>
  <div class='widget story-tree'>
    <h3>Story tree navigator</h3>
    <div class='story-list'>
      <ol>
       <% @placemark.all_prev.each do |placemark| %>
        <li><%= link_to placemark.name, edit_story_placemark_path(@story, placemark), data: {no_turbolink: true} %></li>
      <% end %>
        <li class='current-placemark'><%= @placemark.name %></li>
       <% @placemark.all_next.each do |placemark| %>
        <li><%= link_to placemark.name, edit_story_placemark_path(@story, placemark), data: {no_turbolink: true} %></li>
      <% end %>
      </ol>
    </div>
  </div>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <%= f.hidden_field :image_data %>
  <%= f.hidden_field :image_alt %>
  <div class='widget save-buttons'>
    <%= f.submit 'Save Placemark' %>
    <%= f.submit 'Finish Story' %>
  </div>
<% end %>
<script>
  main('<%= Rails.application.secrets.mapbox_token %>');
</script>

app/views/placemarks/new.html.erb
<h2> New Placemark: <%= @story.name %></h2>
<% if @placemark.errors.any? %>
  <div class='alert red-alert'>
    <h3><%= pluralize(@placemark.errors.count, 'error') %> prevented this placemark from being saved:</h3>
    <ul>
    <% @placemark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% if @placemark.errors[:lat].any? || @placemark.errors[:lng].any? %>
    <% @location_selector_status = 'field_with_errors' %>
  <% end %>
<% end %>
<div class='widget placemark-entry'>
<%= form_for [@story, @placemark] do |f| %>
  <h3>Enter story fragment text</h3>
    <%= f.text_field :name,
                     placeholder: 'Required: Enter a title for this story fragment',
                     autofocus: true,
                     autocomplete: :off %>
    <%= f.text_area  :description,
                     placeholder: 'Optional: Enter a description for this story fragment',
                     autocomplete: :off %>
    <%= f.text_field :link,
                     placeholder: 'Optional: Add a hyperlink to include with this placemark',
                     autocomplete: :off %>                   
  </div>
  <div class='location-selector <%= @location_selector_status %>'>
    <div id='map'>
      <pre id='coordinates' class='ui-coordinates'></pre>
    </div>
    <div class='caption'>
      Drag <i class='fa icon-map-marker-reticule'></i> to set location. Use <i class='fa icon-search fa-fw'></i> to find address or <i class='fa icon-map-marker-current fa-fw'></i> to use current.
    </div>
  </div>
  <div class='widget image-editor'>
    <h3>Optional: Upload and crop image</h3>
      <div class="image-widget-container">
      <div class='cropit-image-preview'></div>
      <div class='image-controls'>
       <button class='select-image-button' type='button'>Select Image</button>
       <input type='range' class='cropit-image-zoom-input'>
       <div class='image-size-label'>Zoom</div>
        <textarea class='image-alt' placeholder='Enter image alt text' autocomplete='off' type='text' name='alt_text' id='alt_text'></textarea>
      </div>
      <input type='file' class='cropit-image-input'>
    </div>
  </div>
  <div class='widget story-tree'>
    <h3>Story tree navigator</h3>
    <div class='story-list'>
      <ol>
      <% @story.placemarks.each do |placemark| %>
       <% if placemark.id %>
        <li><%= link_to placemark.name, edit_story_placemark_path(@story, placemark), data: {no_turbolink: true} %></li>
        <% end %>
       <% end %>
        <li class='current-placemark'>Current Placemark</li>
      </ol>
    </div>
  </div>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <%= f.hidden_field :image_data %>
  <%= f.hidden_field :image_alt %>
  <div class='widget save-buttons'>
    <%= f.submit 'Save Placemark' %>
    <%= f.submit 'Finish Story' %>
  </div>
<% end %>
<script>
  $('.story-list').scrollTop($('.story-list')[0].scrollHeight);
  main('<%= Rails.application.secrets.mapbox_token %>');
</script>

app/views/stories/_form.html.erb
<% if @story.errors.any? %>
  <div class='alert red-alert'>
    <h3><%= pluralize(@story.errors.count, 'error') %> prevented this story from being saved:</h3>
    <ul>
    <% @story.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @story, html: {class: "story-entry"} do |f| %>
  <%= f.text_field :name,
                   placeholder: 'Enter new story name',
                   autofocus: true,
                   autocomplete: :off %>
  <%= f.text_area  :description,
                   placeholder: 'Enter a brief synopsis',
                   autocomplete: :off,
                   class: 'new-story'%>
  <%= f.submit class: 'new-story' %>
<% end %>

app/views/stories/_indexpage_login_notice.html.erb
<div class='alert blue-alert'>
  <h3>Guest user notice:</h3>
  <p>
    Only registered users can permanently store their stories to this gallery; this is the only way we can keep everyone's maps separated. <strong>When you register, any maps you've worked on will be brought over to your new account.</strong>
  </p>
    <%= link_to 'Login', new_user_session_path, class: 'a-button'  %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'a-button'  %>
</div>

app/views/stories/_newpage_login_notice.html.erb
<div class='alert blue-alert new-blue-alert'>
  <h3>Guest user notice:</h3>
  <p>
    As a guest user, you may create and share maps without restriction, and you will be able to return to completed maps for 7 days by saving their unique URL. However, to permanently save maps to your personal gallery, you must login with an account. <strong>When you register, any maps you've worked on will be brought over to your new account.</strong>
  </p>
    <%= link_to 'Login', new_user_session_path, class: 'a-button' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'a-button' %>
</div>

app/views/stories/_no_placemarks_notice.html.erb
<div class='alert yellow-alert'>
  <h3>This story has no placemarks.</h3>
  <p>
    You started creating this story, but haven't added any placemarks yet. Click the button below to begin adding placemarks.
  </p>
  <%= link_to 'Add Placemarks', new_story_placemark_path(@story), data: {no_turbolink: true}, class: 'a-button' %>
</div>

app/views/stories/_showpage_login_notice.html.erb
<div class='alert blue-alert'>
  <h3>Guest user notice:</h3>
  <p>
    As a guest user, you may return to this map at any time within the next 7 days by accessing the URL listed above. However, to permanently save maps to your personal gallery, you must login with an account. <strong>When you register, this map will be brought over to your new account along with anything else you've worked on during this session.</strong>
  </p>
    <%= link_to 'Login', new_user_session_path, class: 'a-button'  %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'a-button'  %>
</div>

app/views/stories/edit.html.erb
<h2>Edit Map Story</h2>
<%= render 'form' %>

app/views/stories/index.html.erb
<h2>View Map Stories</h2>
<div class='story-index'>
<%= render 'indexpage_login_notice' unless current_user.present? %>
  <% @stories.each do |story| %>
    <div class='widget story'>
    <% unless current_user.present? %>
      <div class="disabled-overlay"></div>
    <% end %>
      <%= link_to story.name, story_path(story) %>
      <div class='story-description'>
        <p><%= story.description %></p>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/stories/map.html.erb
<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <title><%= @story.name %></title>
  <meta name='description' content='<%= @story.description %>- Made With Placemark Story: The easiest way to create and share interactive map stories.'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
  <%= csrf_meta_tags %>
</head>
<body class='map-view'>
  <div id='map'></div>
  <ul id='marker-list'></ul>
  <script>
    initStoryMap('<%= Rails.application.secrets.mapbox_token %>', '<%= story_path(@story) %>');
  </script>
</body>
</html>

app/views/stories/new.html.erb
<h2>New Map Story</h2>
<%= render 'form' %>
<%= render 'newpage_login_notice' unless current_user.present? %>

app/views/stories/show.html.erb
<h2>View Map Story: <%= @story.name %></h2>
<% setPlacemarkViewStatus %>
<%= render 'no_placemarks_notice' if @no_placemarks %>
<div class='widget map-story'>
  <h4>Description:</h4>
  <p><%= @story.description %></p>
  <input type='text' id='map-url' value='<%= request.original_url %>' onMouseup='this.select()'></input>
  <%= link_to 'Show Map', story_map_path(@story), target: '_blank', class: ['a-button', @placemarks_link_class,] %>
  <ul>
    <li><%= link_to 'Edit Basics', edit_story_path(@story), class: @placemarks_owner_class %></li>
    <li><%= link_to 'Edit Placemarks', @no_placemarks? new_story_placemark_path(@story) : edit_story_placemark_path(@story, @placemarks.first), data: {no_turbolink: true}, class: [@placemarks_link_class, @placemarks_owner_class] %></li>
    <li><%= link_to 'Delete', story_path(@story), class: @placemarks_owner_class, method: :delete %></li>
  </ul>
</div>
<%= render 'showpage_login_notice' unless current_user.present? %>

app/views/welcome/index.html.erb
<h2>Tell Your Story With Spatial Impact</h2>
<p class='welcome'>
  Placemark Story is the easiest way to create and share beautiful interactive map stories.
  Simply add content piece-by-piece and assign coordinates to each section through the easy-to-use interface.
</p>
<p class='welcome'>
  Location can be set interactively on a map, using an address or your current location, or even automatically based on the the location your images were captured.
</p>